const menu = [
    {
      id: 1,
      title: 'mobile',
      category: 'electronics',
      bid: 15.99,
      img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSeyEXGaeOlpsh9JUi_Vmd0ieA10r_zcQGVlS4_H2kbjw&s',
      desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
    },
    {
      id: 2,
      title: 'bed',
      category: 'furniture',
      bid: 13.99,
      img: 'https://www.godrejinterio.com/imagestore/B2C/LATTICE05/LATTICE05_A2_803x602.jpg',
      desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
    },
    {
      id: 3,
      title: 'fan',
      category: 'electronics',
      bid: 6.99,
      img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRlxoxjmRUUvCbwotwTTEfrO1aFoHk5nZl92EUn2jbcTA&s',
      desc: `ombucha chillwave fanny pack 3 wolf moon street art photo booth before they sold out organic viral.`,
    },
    {
      id: 4,
      title: 'ipad',
      category: 'electronics',
      bid: 20.99,
      img: 'https://store.storeimages.cdn-apple.com/8756/as-images.apple.com/is/ipad-pro-finish-select-202212-11inch-space-gray-wifi_AV1_FMT_WHH?wid=1280&hei=720&fmt=p-jpg&qlt=95&.v=1670865948534',
      desc: `Shabby chic keffiyeh neutra snackwave pork belly shoreditch. Prism austin mlkshk truffaut, `,
    },
    {
      id: 5,
      title: 'jeep',
      category: 'vehicle',
      bid: 22.99,
      img: 'https://img.onmanorama.com/content/dam/mm/en/business/autos/images/2019/8/15/jeep.jpg.transform/schema-4x3/image.jpg',
      desc: `franzen vegan pabst bicycle rights kickstarter pinterest meditation farm-to-table 90's pop-up `,
    },
    {
      id: 6,
      title: 'car',
      category: 'vehicle',
      bid: 18.99,
      img: 'https://cdni.autocarindia.com/utils/imageresizer.ashx?n=https://cms.haymarketindia.net/model/uploads/modelimages/Hyundai-Grand-i10-Nios-200120231541.jpg&w=872&h=578&q=75&c=1',
      desc: `Portland chicharrones ethical edison bulb, palo santo craft beer chia heirloom iPhone everyday`,
    },
    {
      id: 7,
      title: 'chair',
      category: 'furniture',
      bid: 8.99,
      img: 'https://cdn.moglix.com/p/djsrKBRPVjQIC-xxlarge.jpg',
      desc: `carry jianbing normcore freegan. Viral single-origin coffee live-edge, pork belly cloud bread iceland put a bird `,
    },
    {
      id: 8,
      title: 'sofa',
      category: 'furniture',
      bid: 12.99,
      img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRQLZjn9EDgfzvcARLNNb5pOcLyvsnG3MRbv4Rx7Joezw&s',
      desc: `on it tumblr kickstarter thundercats migas everyday carry squid palo santo leggings. Food truck truffaut  `,
    },
    {
      id: 9,
      title: 'computer',
      category: 'electronics',
      bid: 16.99,
      img: 'https://img.etimg.com/thumb/width-1200,height-900,imgsize-74560,resizemode-75,msid-104220582/top-trending-products/electronics/laptops/best-gaming-computer-sets-for-an-unparalleled-experience-starting-at-just-23999.jpg',
      desc: `skateboard fam synth authentic semiotics. Live-edge lyft af, edison bulb yuccie crucifix microdosing.`,
    },
  ];
  export default menu;
  
