name: SonarCloud analysis

on:
  push:
    branches: [ "main" ]

jobs:
  Analysis:
    runs-on: ubuntu-latest

    steps:
      # ✅ Step 1: Checkout code (VERY IMPORTANT)
      - name: Checkout code
        uses: actions/checkout@v4

      # ✅ Step 2: SonarCloud scan
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=somyagupta752_Auction-Platform
            -Dsonar.organization=auctionplatform
